### PR TITLE
LA 2253, LA-2255 code customizing to our need

### PR DESCRIPTION
**Pull request by pepcus-Aish**
We are now changing the code to our library needs.

"JSONViewer" code is now removed from "JSONEditor" component. it will not have the functionality of viewer which is not required in our library. removed the import from code.
image

### CODE REVIEW

**Comment by Nikmahajan** [comment]
Please add proper titles to the PR's.

**Comment by Nikmahajan** [comment]
We should not remove the functionality! We can make it configurable/controllable.

**Comment by pepcus-Aish** [comment]
@Nikmahajan Ok Nikhil I will work on it to make it more configurable and controllable

**Comment by pepcus-Aish** [comment]
@Nikmahajan ,adding back viewer functionality code on the JSONE editor that will be props-driven.

**Comment by pepcus-Aish** [comment]
Added the code for JSON viewer, If a user needs the dual view both for editor and viewer he could have by passing prop "view"={'dual'} .
image

**Review by Nikmahajan — APPROVED** [review]

**Pull request merged**
